service: shopping-service

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-webpack

functions:
  suggest:
    handler: shopping-service.suggestWardrobe
    name: ${self:provider.stage}-lambda
    description: Provides wardrobe suggestions based on a given location

    events:
     - http:
        path: suggest
        method: get