service: shopping-service

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-webpack

functions:
  GetSuggestion:
    handler: shopping-service.Suggest

    events:
     - http:
        path: suggest
        method: get